############################
# configsql.toml
############################
default_schema_sql = '''
-- images table

CREATE TABLE IF NOT EXISTS images (
    image_id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_path TEXT UNIQUE,
    image_width INTEGER,
    image_height INTEGER,
    timestamp TEXT
);

SELECT AddGeometryColumn(
    'images',            -- Table name
    'location',          -- Column name
    4326,                -- SRID (-1 or 0 signifies flat pixel/Cartesian space)
    'POINT',             -- Geometry type
    'XY'                 -- 2D coordinates
);

SELECT CreateSpatialIndex('images', 'location');

-- trees table

CREATE TABLE IF NOT EXISTS trees (
    tree_id INTEGER PRIMARY KEY AUTOINCREMENT,
    image_id INTEGER,
    class_id INTEGER,
    confidence REAL,
    tree_touches_edge INTEGER DEFAULT 0,
    FOREIGN KEY (image_id) REFERENCES images (image_id) ON DELETE CASCADE 
);

SELECT AddGeometryColumn(
    'trees',             -- Table name
    'tree_poly',              -- Column name
    0,                   -- SRID (-1 or 0 signifies flat pixel/Cartesian space)
    'POLYGON',           -- Geometry type
    'XY'                 -- 2D coordinates
);

SELECT CreateSpatialIndex('trees', 'tree_poly');

-- damage table

CREATE TABLE IF NOT EXISTS damage (
    damage_id INTEGER PRIMARY KEY, 
    image_id INTEGER,
    tree_id INTEGER, 
    FOREIGN KEY (tree_id) REFERENCES trees(tree_id) ON DELETE CASCADE
);

    SELECT AddGeometryColumn(
    'damage',            -- Table name
    'damage_poly',              -- Column name
    0,                   -- SRID (-1 or 0 signifies flat pixel/Cartesian space)
    'POLYGON',           -- Geometry type
    'XY'                 -- 2D coordinates
);

SELECT CreateSpatialIndex('damage', 'damage_poly');
'''

#############################

postprocessing_sql = '''
-- flip ys in tree contours so they overlay images

UPDATE trees 
SET tree_poly = ATM_Transform(tree_poly, ATM_CreateScale(1, -1));

-- flip ys in damage contours so they overlay images

UPDATE damage 
SET damage_poly = ATM_Transform(damage_poly, ATM_CreateScale(1, -1));

/**********************************************************************************
Calculates proximity of each tree polygon to the left, right an top edge the image.
Proximity is expressed as a proportion of image width or image height.

trees.tree_touches_edge is set to 1 if proximity is less that a specified threshold
or 0 otherwise.

It is assumed tree.poly is scaled with x ranging from 0 to page_width with 0 at the
left of the image and y ranging from 0 to -page_height with 0 at the top of the 
image.
*/

CREATE TEMP TABLE temp_touches AS 
SELECT 
  trees.image_id, 
  tree_id,
  MbrMinX(tree_poly)/image_width AS left_proximity,
  1 - MbrMaxX(tree_poly)/image_width AS right_proximity,
  - MbrMaxY(tree_poly)/image_height AS top_proximity
FROM trees, images
WHERE trees.image_id=images.image_id;

UPDATE trees
SET tree_touches_edge = left_proximity<0.01 OR right_proximity<0.01 OR top_proximity<0.01
FROM temp_touches
WHERE trees.tree_id = temp_touches.tree_id;
'''

update_tree_class_sql = '''
UPDATE trees
SET tree_class = cluster2class.tree_class
FROM cluster2class
WHERE trees.soft_tree_class = cluster2class.tree_cluster;
'''

##################################################################
create_v_tree_poly_view_sql = '''
CREATE VIEW v_tree_poly AS
SELECT tree_id, image_height, image_width, tree_poly
FROM images, trees
WHERE images.image_id = trees.image_id
'''

