# config.toml

[database]
db_path = '/home/aubrey/Desktop/Efate2025/Efate2025B.db'
db_backup_dir = 'db_backups'

[trees]
model_path = 'hdbscan_pipeline_1.joblib'
gallery_dir = 'tree_cluster_gallery_1'
images_per_cluster = 35
min_prob = 0.2
csv_path = 'cluster2class.csv'

[damage]
order = 14
minpixels = 50
