# config.toml

[database]
delete_db = true           # If true, database named db_path will be deleted at start of processing.
db_path = 'test.db'          # Name of current database, name of database to be created at start of processing
db_backup_dir = 'db_backups' # backup directory for databases

[trees]
model_path = 'hdbscan_pipeline_1.joblib'
gallery_dir = 'tree_cluster_gallery_1'
images_per_cluster = 35
min_prob = 0.2
csv_path = 'cluster2class.csv'

[damage]
order = 14
minpixels = 50
